### PR TITLE
update clementine-latest: fix url

### LINKED ISSUE #5895: Cask clementine-latest doesn't load the latest version of clementine
#### General troubleshooting steps

- [X] I have retried my command with `--force` and the issue is still present.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
  - [ ] None of the templates was appropriate for my issue, or I’m not sure.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I think the expression in that following code piece has no influence on the sorting of the index on the site. I try the url with the appendix ?C=M;O=D with the browser.
You can't sort manually the index on this site.
I think the url of the latest version must manually written in the cask like in other cask.
Or another solution?

#### Command that failed

```
last_modified_query = '?C=M;O=D'
    base_url = 'https://builds.clementine-player.org/mac/'
    file = URI("#{base_url}#{last_modified_query}")
```

#### Output of command with `--force --verbose --debug`

```
First Part of output with download from the app
MacBook-Air-HR-2:homebrew-cask user$ brew cask uninstall clementine-latest
==> Uninstalling Cask clementine-latest
==> Backing App 'Clementine.app' up to '/usr/local/Caskroom/clementine-latest/latest/Clementine.app'.
==> Removing App '/Applications/Clementine.app'.
==> Purging files for version latest of Cask clementine-latest
MacBook-Air-HR-2:homebrew-cask roewer$ brew cask install clementine-latest --verbose --debug
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask-versions).
No changes to formulae.

==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://builds.clementine-player.org/mac/clementine-1.0-111-g8582253.dmg
/usr/bin/curl -q --show-error --user-agent Homebrew/1.6.9 (Macintosh; Intel Mac OS X 10.13.5) curl/7.54.0 --fail --location --remote-time --continue-at - --output /Users/user/Library/Caches/Homebrew/Cask/clementine-latest--latest.dmg.incomplete https://builds.clementine-player.org/mac/clementine-1.0-111-g8582253.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 23.4M  100 23.4M    0     0  1397k      0  0:00:17  0:00:17 --:--:-- 1417k
==> Downloaded to -> /Users/user/Library/Caches/Homebrew/Cask/clementine-latest--latest.dmg
==> Verifying download
```

#### Output of `brew tap`

```
homebrew/bundle
homebrew/cask
homebrew/cask-versions
homebrew/core
homebrew/dupes
homebrew/fuse
homebrew/services
pr0d1r2/contrib
scribusproject/scribus
vitorgalvao/tiny-scripts
```

### PR DESCRIPTION
**Pull request by yurikoles**
closes #5895

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask-versions/pulls
[closed issues]: https://github.com/Homebrew/homebrew-cask-versions/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by yurikoles** [comment]
@commitay fixed

**Comment by yurikoles** [comment]
@commitay bump?

File: Casks/clementine-latest.rb [hunk 1]
```diff
@@ -6,12 +6,28 @@
...
+    files = URI("#{base_url}#{last_modified_query}")
+            .open
+            .read
+            .scan(%r{href="(clementine-[^"]+.dmg)"})
+
+    versions_array = []
+    files.each do |file|
+      version_string = file[0].split('clementine-')[1].split('.dmg')[0]
+
+      if version_string.include? '1.3.1-'
```
Comment (commitay) [inline Casks/clementine-latest.rb]: This would still need to be updated which is what we are trying to avoid by using `url do`.

**Comment by yurikoles** [comment]
@commitay, I had updated formula. But I'm still not sure about RCs. `Gem::Version` sort puts RCs of `1.3.1` higher then other builds with this version, which is correct. The issue is that upstream has not updated version in repo and new builds has same version, which is already released.

**Comment by yurikoles** [comment]
@commitay bump?

File: Casks/clementine-latest.rb [hunk 2]
```diff
@@ -4,14 +4,29 @@
...
-    file = URI("#{base_url}#{last_modified_query}")
-           .open
-           .read
-           .scan(%r{href="(clementine-[^"]+.dmg)"})
-           .flatten
-           .first
+    files = URI(base_url.to_s)
+            .open
+            .read
+            .scan(%r{href="(clementine-[^"]+.dmg)"})
```
Comment (reitermarkus) [inline Casks/clementine-latest.rb]: Add `.flatten` here.

File: Casks/clementine-latest.rb [hunk 3]
```diff
@@ -4,14 +4,29 @@
...
+
+    versions_array = []
+    files.each do |file|
+      version_string = file[0].split('clementine-')[1].split('.dmg')[0]
```
Comment (reitermarkus) [inline Casks/clementine-latest.rb]: Remove `[0]` here, and use a regex to extract the version, something like this:

```ruby
file[%r{clementine-(.*)\.dmg}, 1]
```

File: Casks/clementine-latest.rb [hunk 4]
```diff
@@ -4,14 +4,29 @@
...
+
+      next unless version_string.index(%r{-((\d+).?)+-(\w)+})
```
Comment (reitermarkus) [inline Casks/clementine-latest.rb]:
```ruby
if version_string !~ %r{-((\d+).?)+-(\w)+}
```

Comment (reitermarkus) [reply Casks/clementine-latest.rb]: What is this checking exactly?

File: Casks/clementine-latest.rb [hunk 5]
```diff
@@ -4,14 +4,29 @@
...
-           .scan(%r{href="(clementine-[^"]+.dmg)"})
-           .flatten
-           .first
+    files = URI(base_url.to_s)
+            .open
+            .read
+            .scan(%r{href="(clementine-[^"]+.dmg)"})
+
+    versions_array = []
+    files.each do |file|
```
Comment (reitermarkus) [inline Casks/clementine-latest.rb]:
```ruby
versions_array = files.map { … }.compact
```

File: Casks/clementine-latest.rb [hunk 6]
```diff
@@ -4,14 +4,29 @@
...
+      version_string = file[0].split('clementine-')[1].split('.dmg')[0]
+
+      next unless version_string.index(%r{-((\d+).?)+-(\w)+})
+      gem_version = Gem::Version.new(version_string)
+      next unless gem_version
```
Comment (reitermarkus) [inline Casks/clementine-latest.rb]: Remove this, `Gem::Version.new` can never be `nil`.

File: Casks/clementine-latest.rb [hunk 7]
```diff
@@ -4,14 +4,29 @@
...
+      versions_array.push(gem_version: gem_version, string: version_string)
+    end
+
+    versions_array.sort! do |a, b|
```
Comment (reitermarkus) [inline Casks/clementine-latest.rb]: Since `Gem::Version.new` can never be `nil` and we don't need it for anything else, you can do this:

```ruby
.sort_by { |version| Gem::Version.new(version) }
```

**Comment by yurikoles** [comment]
how to delete/skip version and avoid future delete_if on array?

**Comment by reitermarkus** [comment]
Use the `%r{-((\d+).?)+-(\w)+}` regex inside the first regex, then you don't have to delete afterwards.

**Comment by yurikoles** [comment]
bump?

**Comment by reitermarkus** [comment]
You haven't addressed my comment.

File: Casks/clementine-latest.rb (hunk 4 above)
Comment (reitermarkus) [reply Casks/clementine-latest.rb]: The `.` should be escaped then.

**Comment by yurikoles** [comment]
@reitermarkus 

```ruby
    versions_array = files.map do |file|
      file[%r{-((\d+)\.?)+-(\w)+}] # E.g. 1.3.1-467-g2b280de
    end.compact
```
produces error:
```
audit for clementine-latest: failed
 - exception while auditing clementine-latest: Malformed version number string -1.0-111
Error: audit failed for casks: clementine-latest
```

File: Casks/clementine-latest.rb (hunk 4 above)
Comment (yurikoles) [reply Casks/clementine-latest.rb]: done

**Comment by reitermarkus** [comment]
It should be 

```ruby
file[%r{clementine\-((\d+\.?)+\-\w+)\.dmg}, 1]
```

**Comment by yurikoles** [comment]
it produces URL: `https://builds.clementine-player.org/mac/clementine-.dmg`

**Comment by yurikoles** [comment]
@reitermarkus thanks, I think it's now ready for merge.

**Comment by reitermarkus** [comment]
You can now just use this regex for the `.scan`, actually.

**Comment by yurikoles** [comment]
but now there is garbage "1" array elements after each version

**Comment by reitermarkus** [comment]
Did you have it like this?

```ruby
.scan(%r{href="clementine\-((\d+\.?)+\-\d+\-\w+)\.dmg"})
```

**Comment by yurikoles** [comment]
Yes, the files array looks like:
```
1.0-111-g8582253
0
1.0-112-g0c5f422
0
```
There also may be 1,2,3 instead of 0.

**Comment by reitermarkus** [comment]
Ah, probably because the regex has two groups, try this:

```ruby
.scan(%r{href="clementine\-((?:\d+\.?)+\-\d+\-\w+)\.dmg"})
```

**Comment by yurikoles** [comment]
@reitermarkus it's fixed now, thanks.

**Comment by reitermarkus** [comment]
Thanks, @yurikoles!
